server:
  listen_address: 127.0.0.1:2022

  # Host private key files.
  # If unspecified, null or empty, an RSA, ECDSA and Ed25519 key will be generated and stored.
  host_keys: null

logging:
  # The log file to output activity logs to. Debug and error logs are still written to standard error.
  # If unspecified or null, activity logs are written to standard out.
  file: null

auth:
  # Allow clients to connect without authenticating.
  no_auth: false

  # The maximum number of authentication attempts permitted per connection.
  # If set to a negative number, the number of attempts are unlimited.
  # If unspecified, null or zero, a sensible default is used.
  max_tries: 0

  password_auth:
    # Offer password authentication as an authentication option.
    enabled: true

  public_key_auth:
    # Offer public key authentication as an authentication option.
    enabled: true

  keyboard_interactive_auth:
    # Offer keyboard interactive authentication as an authentication option.
    enabled: false

    # Instruction for the keyboard interactive authentication.
    instruction: Answer these weird questions to log in!

    questions:
      - text: "User: " # Keyboard interactive authentication question text.
        echo: true # Enable echoing the answer.
      - text: "Password: "
        echo: false

ssh_proto:
  # The version identification string to announce in the public handshake.
  # If unspecified or null, a reasonable default is used.
  # Note that RFC 4253 section 4.2 requires that this string start with "SSH-2.0-".
  version: SSH-2.0-sshesame

  # Sent to the client after key exchange completed but before authentication.
  # If unspecified or null, a reasonable default is used.
  # If empty, no banner is sent.
  banner: This is an SSH honeypot. Everything is logged and monitored.

  # The maximum number of bytes sent or received after which a new key is negotiated. It must be at least 256.
  # If unspecified, null or 0, a size suitable for the chosen cipher is used.
  rekey_threshold: 0

  # The allowed key exchanges algorithms.
  # If unspecified or null, a default set of algorithms is used.
  key_exchanges: null

  # The allowed cipher algorithms.
  # If unspecified or null, a sensible default is used.
  ciphers: null

  # The allowed MAC algorithms.
  # If unspecified or null, a sensible default is used.
  macs: null